const path = require('path')
const express = require('express')
const app = express()
// const server = require('http').Server(app);
const port = 3000
const server = app.listen(port, () => {
	console.log(`listening on ${port}`)
})
const io = require('socket.io')(server,{allowEIO3: true});

app.use('/lib', express.static('static/lib'))
app.use('/mode', express.static('static/mode'))
app.use('/socket.io', express.static('node_modules/socket.io'))
app.set('view engine', 'ejs')
app.set('views', path.join(__dirname,'views'))

var clientSessionMap = {};

io.on('connection', (client) => {
	// clientId is each tab's id, it is generated by socket.io
	// sessionId is each link's id (accessed with .com/sessId), it is generated by the users link
	// multiple clients can be logged into the same session
	client.on('sessId', (data) => {
		clientSessionMap[client.id] = sessId;
	});
	client.on('disconnect', () => {
		delete clientSessionMap[client.id];
	});
});

app.get('/', (req,res) => {
	let randomSessId = Math.random().toString(36).substring(7);
	res.redirect('/'+randomSessId);
});
app.get('/:sessId', (req,res) => {
	sessId = req.params['sessId']
	console.log('get request here', req.params)
	res.render("index", {sessId: sessId})
})

